# Generated by Django 3.2.2 on 2021-06-12 07:04

import app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app_auth.models.user_img_path),
        ),
    ]
